version: "3"
services:
    redis:
        image: redis
        container_name: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        ports:
            - 6379:6379
        volumes:
            - ./redis/data:/data
